version: '3.1'

services:
  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2368:2368"
    environment:
      url: http://192.168.254.142:2368
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost-local.db
    volumes:
      - ./content:/var/lib/ghost/content
    restart: unless-stopped
