services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghost_db
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghostpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: ghost
      database__connection__password: ghostpass
      database__connection__database: ghost_db
      url: http://localhost:2368
    depends_on:
      - mysql
    volumes:
      - ./content:/var/lib/ghost/content

volumes:
  mysql_data: